export type ThemeTokens = {
  controlBorderWidth: string;
  controlButtonRadius: string;
  controlFilterRadius: string;
  controlChipLeftRadius: string;
  controlChipRightRadius: string;
  controlSegmentRadius: string;
  controlSegmentOptionRadius: string;
  appBackground: string;
  surfaceBackground: string;
  borderColor: string;
  textPrimary: string;
  textMuted: string;
  infoText: string;
  primaryActionBackground: string;
  primaryActionText: string;
  secondaryActionBackground: string;
  secondaryActionText: string;
  disabledActionBackground: string;
  disabledActionText: string;
  dangerActionBackground: string;
  dangerActionText: string;
  choiceControlBackground: string;
  choiceControlText: string;
  choiceControlActiveBackground: string;
  choiceControlActiveText: string;
  statusChipBackground: string;
  statusChipText: string;
  filterControlBackground: string;
  filterControlBorder: string;
  filterControlText: string;
  filterControlActiveBackground: string;
  filterControlActiveBorder: string;
  filterControlActiveText: string;
  toggleOnBackground: string;
  toggleOffBackground: string;
  toggleThumbColor: string;
  modalBackdrop: string;
  modalSurfaceBackground: string;
  modalSurfaceBorder: string;
  gridLineColor: string;
  mapBoundaryFill: string;
  mapBoundaryStroke: string;
  mapBedFill: string;
  mapPerennialBedFill: string;
  mapBedStroke: string;
  mapLawnFill: string;
  mapLawnStroke: string;
  mapTreeFill: string;
  mapTreeStroke: string;
  mapShrubFill: string;
  mapShrubStroke: string;
  mapHedgeFill: string;
  mapHedgeStroke: string;
  mapPathFill: string;
  mapPathStroke: string;
  mapWallFill: string;
  mapWallStroke: string;
  mapFenceFill: string;
  mapFenceStroke: string;
  mapTrellisFill: string;
  mapTrellisStroke: string;
  mapPatioFill: string;
  mapPatioStroke: string;
  mapDeckFill: string;
  mapDeckStroke: string;
};

export const DEFAULT_THEME_TOKENS: ThemeTokens = {
  controlBorderWidth: "1",
  controlButtonRadius: "10",
  controlFilterRadius: "10",
  controlChipLeftRadius: "8",
  controlChipRightRadius: "999",
  controlSegmentRadius: "12",
  controlSegmentOptionRadius: "8",
  appBackground: "#F0F6EE",
  surfaceBackground: "#FFFFFF",
  borderColor: "#D8E5D5",
  textPrimary: "#1E402C",
  textMuted: "#4E6857",
  infoText: "#587063",
  primaryActionBackground: "#DFEADF",
  primaryActionText: "#1F3F2B",
  secondaryActionBackground: "#DFEADF",
  secondaryActionText: "#1F3F2B",
  disabledActionBackground: "#A0B2A4",
  disabledActionText: "#FFFFFF",
  dangerActionBackground: "#C74C3A",
  dangerActionText: "#FFFFFF",
  choiceControlBackground: "#E8F2E7",
  choiceControlText: "#2A4B38",
  choiceControlActiveBackground: "#1E6A42",
  choiceControlActiveText: "#FFFFFF",
  statusChipBackground: "#EDF5EC",
  statusChipText: "#2A4B38",
  filterControlBackground: "#F7FBF5",
  filterControlBorder: "#A9C3AC",
  filterControlText: "#2A4B38",
  filterControlActiveBackground: "#1E6A42",
  filterControlActiveBorder: "#1E6A42",
  filterControlActiveText: "#FFFFFF",
  toggleOnBackground: "#2D6A49",
  toggleOffBackground: "#BFD1BC",
  toggleThumbColor: "#FFFFFF",
  modalBackdrop: "#00000066",
  modalSurfaceBackground: "#FFFFFF",
  modalSurfaceBorder: "#D8E5D5",
  gridLineColor: "#14432E4D",
  mapBoundaryFill: "#2762421F",
  mapBoundaryStroke: "#2D6A49",
  mapBedFill: "#3582524D",
  mapPerennialBedFill: "#2E5C8F4D",
  mapBedStroke: "#101010",
  mapLawnFill: "#6FAB5F38",
  mapLawnStroke: "#101010",
  mapTreeFill: "#216C3C4D",
  mapTreeStroke: "#1A5C35",
  mapShrubFill: "#60A85F47",
  mapShrubStroke: "#3B7F45",
  mapHedgeFill: "#3F824942",
  mapHedgeStroke: "#2D7A40",
  mapPathFill: "#9A9A9A47",
  mapPathStroke: "#7A7A7A",
  mapWallFill: "#76767659",
  mapWallStroke: "#4D4D4D",
  mapFenceFill: "#916A4A4D",
  mapFenceStroke: "#7F5738",
  mapTrellisFill: "#BBAB4C4D",
  mapTrellisStroke: "#9F8D2E",
  mapPatioFill: "#94949452",
  mapPatioStroke: "#6A6A6A",
  mapDeckFill: "#93673E52",
  mapDeckStroke: "#7A4E2B",
};

export function mergeThemeTokens(input?: Partial<ThemeTokens> | null): ThemeTokens {
  return {
    ...DEFAULT_THEME_TOKENS,
    ...(input ?? {}),
  };
}
